[tool.poetry]
name = "repl_python3_com411"
version = "0.1.0"
description = ""
authors = ["AagashUni21 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
tui = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
